let products = [
  {
    id: 1,
    name: "Samyang Sauce",
    price: 400,
    des: "It is a buldak sauce",
  },
  {
    id: 2,
    name: "Heinz Mayonnaise",
    price: 550,
    des: "It is a mayonnaise",
  },
  {
    id: 3,
    name: "Lays Chips",
    price: 50,
    des: "It is a lays chips",
  },
  {
    id: 4,
    name: "Dairy Milk",
    price: 350,
    des: "It is dairy milk",
  },
  {
    id: 5,
    name: "Buldak Noodles",
    price: 480,
    des: "It is spicy noodles",
  },
  {
    id: 6,
    name: "Burger",
    price: 500,
    des: "It is spicy burger",
  },
  {
    id: 7,
    name: "Sandwich",
    price: 320,
    des: "It is spicy sandwich",
  },
  {
    id: 8,
    name: "Coca Cola",
    price: 150,
    des: "2 Litr",
  },
  {
    id: 9,
    name: "Mirinda",
    price: 150,
    des: "2 Litr",
  },
  {
    id: 10,
    name: "IPhone",
    price: 150000,
    des: "15 Pro Model",
  },
  {
    id: 11,
    name: "Samsung",
    price: 86000,
    des: "galaxy s23 Model",
  },
  {
    id: 12,
    name: "PS5",
    price: 86000,
    des: "5th Model",
  },
  {
    id: 13,
    name: "Ryzen HP",
    price: 156000,
    des: "9th Model",
  },
  {
    id: 14,
    name: "Cheetoz Chips",
    price: 320,
    des: "Its Cheetoz",
  },
  {
    id: 15,
    name: "Ramen Noodles",
    price: 460,
    des: "Its Ramen Spicy",
  },
  {
    id: 16,
    name: "Fruit Cake",
    price: 287,
    des: "Its made of fruit",
  },
  {
    id: 17,
    name: "Birthday Cake",
    price: 2089,
    des: "1 pound cake",
  },
  {
    id: 18,
    name: "Pringles Chips",
    price: 326,
    des: "Pringles life",
  },
  {
    id: 19,
    name: "KFC Chicken Bucket",
    price: 1026,
    des: "Fingers lickin good!",
  },
  {
    id: 20,
    name: "Shawarma",
    price: 178,
    des: "Chicken shawarma",
  },
  {
    id: 21,
    name: "Fanta",
    price: 80,
    des: "Fanta orange",
  },
  {
    id: 22,
    name: "Rice Bowl",
    price: 256,
    des: "Chicken fry with veg",
  },
  {
    id: 23,
    name: "Joystick",
    price: 2554,
    des: "Gameplay joystick",
  },
  {
    id: 24,
    name: "JavaScript Book",
    price: 512,
    des: "JavaScript Master",
  },
  {
    id: 25,
    name: "React Book",
    price: 654,
    des: "Reactive React",
  },
  {
    id: 26,
    name: "Python Book",
    price: 555,
    des: "Make it python",
  },
  {
    id: 27,
    name: "Keyboard & Mouse",
    price: 1234,
    des: "A4 Tech",
  },
];
